services:
  ghost:
    image: ghost:6-alpine
    restart: always
    ports:
      - ${GHOST_LOCAL_PORT}:2368
    environment:
      url: ${GHOST_LOCAL_URL}
      NODE_ENV: ${NODE_ENV}
      database__client: sqlite3
      database__connection__filename: /var/lib/ghost/content/data/ghost.db
    volumes:
      - ghost-data:/var/lib/ghost/content
      - ./routes.yaml:/var/lib/ghost/content/settings/routes.yaml
      - ./theme:/var/lib/ghost/content/themes/random-theme

  theme-builder:
    image: node:22-alpine
    working_dir: /theme
    volumes:
      - ./theme:/theme
      - theme_node_modules:/theme/node_modules
    command: sh -c "npm ci && npm run build"
    restart: "no"

volumes:
  ghost-data:
  theme_node_modules:
