routes:
  /article/:
    controller: channel
    template: listArticles
    limit: 12

collections:
  /:
    permalink: /{slug}/
    template: index
    filter: 'tag:-[hash-news]'

taxonomies:
  tag: /tag/{slug}/
  author: /author/{slug}/